[package]
name = "zk_iot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ark-ff = "0.4.2"
nalgebra = "0.32.6"
rand = "0.8.5"
rustnomial = "0.3.2"
serde = "1.0.208"
serde_json = "1.0.125"
sha2 = "0.10.8"
